author,updated_at,like_count,text,public
@nikasxirtladze3325,2024-05-16T16:27:28Z,1,*—á—Ç*,True
@pakpukik6417,2024-05-15T05:17:16Z,0,"Is the try-except mechanism considered best practice, or is it better to avoid?",True
@RohitTiwari-mo8mi,2024-05-02T11:41:06Z,0,Excellent!,True
@papacore73,2024-04-11T15:08:43Z,0,Clear and concise. Thanks!!!,True
@teclote,2024-03-21T15:24:18Z,0,"Outstanding, thank you",True
@rockelleg.3406,2023-12-04T13:08:30Z,0,thank you so much,True
@VISHNUSINGH-gi8rd,2023-11-30T17:58:56Z,0,"Also, if an exception is raised in the try block the lines of code below that line in the try block aren't executed so better to write only the risky stuff in the try block.",True
@morteza1736,2023-09-14T09:59:32Z,0,5:24 THIS IS MUCH MORE EASIER THAN READING TRACEBACK ERROR!!!!!! Thank you So much,True
@gobbogrob,2023-08-24T15:13:18Z,0,perfect!!,True
@johnyjohnjohnson1317,2023-07-04T18:51:26Z,0,the finally thing seems unececary . its like :   if True:      ....  but im shure it has some purpose that i dont know.,True
@markkennedy9767,2023-05-27T19:04:24Z,0,"At 7:00, when you put that code in the else clause instead of the try clause, could you get a traceback due to this code in the else clause.  If so, is such a traceback generally regarded as preferable to any confusion that may arise from any exception thrown by this code if it was put in the try clause.  Basically, I suppose I'm asking is a traceback generally preferable to a confusing exception. And is that the reason we would put that code in the else clause as you did. Thanks.",True
@cefalopodo5717,2023-05-03T22:35:44Z,0,"""currupt""",True
@gama1123,2023-04-20T21:55:52Z,1,*corrupt,True
@PianoShawn,2023-04-16T02:34:16Z,0,"thx man ,u are a life saver",True
@austinmorara7954,2023-04-15T10:32:31Z,0,"commenting seven years laterüòÇThank you for creating this video, Its really helped me understand Exceptions better.",True
@junhuama68,2023-04-09T18:18:03Z,0,love your southern accent,True
@salarghaffarian9745,2023-03-22T20:42:48Z,0,Thanks for this great content.,True
@kdSU30,2023-03-02T21:45:19Z,0,1:21 2:40 4:34 the most crucial messages of this video!,True
@raymanzarek3922,2023-02-18T13:33:13Z,0,Thx,True
@debatradas1597,2023-01-26T15:41:05Z,0,thanks,True
@hudaal-hadi6705,2022-12-24T23:56:37Z,0,It is disappointing that you are no longer upload videosüò¢,True
@PHXKHEEDGAMING,2022-12-19T10:34:56Z,0,There is no use-case of ‚ÄòFileNotFoundError‚Äô in this tutorial or I did miss it??  That didn‚Äôt seem like a key word or an inbuilt function.    Help,True
@pallekjrlaursen8388,2022-12-07T18:04:38Z,0,Very nice video.,True
@twattusbobble9845,2022-11-30T18:20:14Z,6,I have just been battling all day with coding challenges in MIT intro to computer science for the error handling section. I've watched this video once and I now get it perfectly. You're really really good at explaining stuff!,True
@clazzo8849,2022-11-13T09:13:00Z,0,how do i bypass a 403 forbidden 5007 error,True
@bushraw66,2022-11-12T15:04:36Z,1,THANK YOU,True
@deepakpratap3792,2022-11-01T05:39:44Z,0,Best teacher..Thanks a ton,True
@smelly_code_odor_coder,2022-10-26T19:40:17Z,0,"So basically try and except is made for other people who'll use your code, not you? Kinda like documentation? I built a fairly large application recently and I never once needed try and except because if an error occurred I knew where it was coming from but if someone else way later is using one of your modules for something, it's much easier to understand what error they made right off the bat via exception handling?  Someone please answer me. I dont understand why you'd want this.",True
@cach_dies,2022-10-26T06:01:49Z,0,Could you do an updated video with 3.11 features?,True
@brolord1288,2022-10-17T07:40:19Z,0,"That moment when you like a video you already liked :) Great tutorial, thanks!",True
@krynixlegion3982,2022-09-14T18:36:57Z,0,Oh My God Thank You So Much  You Helped Me Sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo much!,True
@reddrive,2022-09-10T04:55:09Z,0,Nicely done,True
@muralimohan7005,2022-09-10T00:26:56Z,0,Very good explanation üëç,True
@thienviet3429,2022-08-17T15:37:21Z,0,"Thanks, the new thing I know from this video is: ""While you can already write two except, you are destroyed by 'except NameError and ValueError: '""",True
@gabrielblanco2969,2022-08-16T20:53:15Z,0,"try:     80 lines of code except:     print(""Error connecting the DB"")",True
@leelasaivoonna1728,2022-07-25T08:28:57Z,0,"Like god bless you!, here programmers bless you..!!",True
@martin19,2022-07-20T13:55:11Z,0,Thanks dude!,True
@oluwatobilobaadeyemi2008,2022-07-18T11:42:54Z,0,This is a great. Simple clear concise.Thank you,True
@joeyzalman8254,2022-07-06T11:21:15Z,0,very clear thank you!,True
@nravikiran4661,2022-06-27T09:42:45Z,1,Thank you,True
@Flugfritze96,2022-06-19T15:09:12Z,0,<3,True
@schnitzelen2,2022-06-15T12:52:17Z,0,"Very nice explanation, greatly appreciated! üôÇ",True
@rezamostafid8810,2022-06-12T07:26:56Z,0,Corey: very clear and useful introduction of all the main features and caveats....better than the Python book I'm current using to learn python. I'm not sure if you did this intentionally but you mention some points at the beginning ( and also later on ... ) that provide the motivation for exceptions to begin with. This in turn allows much better understanding of the 'else' and 'finally' clauses as well as the 'raise' Thanks for clearing the fog in my head!,True
@sikshamovement7516,2022-06-04T09:15:59Z,0,Superb,True
@quifix2506,2022-05-28T13:03:38Z,0,thanks,True
@rahulstudies1178,2022-05-27T13:50:10Z,0,amazing content sir,True
@gordhenschel1419,2022-04-30T12:30:42Z,0,currupt spelling exception.,True
@DanielkaElliott,2022-04-27T16:16:56Z,0,if all this was within a loop you wouldn't put close() under an else statement right??,True
@sammavrs,2022-04-22T21:51:25Z,0,"always a great feeling when my ""professor"" links your videos. STUDENT LOANS HERE I COME!!",True
@harivignesh1623,2022-04-11T02:57:00Z,0,Awesome,True
@letronix6243,2022-03-15T05:43:57Z,0,i still don't understand why you need finally. you can just leave it out,True
@genem5659,2022-03-11T04:35:27Z,0,"7 years later, this tutorial is still helping people! xoxo",True
@mehdia5810,2022-03-05T18:49:42Z,0,"Question: Could we change the error message, without stopping the program from the interruption? Normal error handling, doesn't terminate the program and you would notice the message printed by programmer. I'd like the program to break but a different error massage be shown. is it possible?",True
@stephonhenry-rerrie3997,2022-03-04T17:04:57Z,0,Great video. You spelled ‚Äúcorrupt‚Äù wrong,True
@Jure1234567,2022-02-26T07:21:26Z,0,"You haven't said, why finally is needed, cuz you could just put finalizing code after try block",True
@Sneaadler,2022-02-18T12:51:42Z,0,"I love that you, visulize this with a real error insted of faking one",True
@user-qn5by5iv7u,2022-02-13T08:39:58Z,0,2022,True
@Tahazif_TheCool22,2022-02-13T06:23:33Z,0,love this video!,True
@alalhaj220,2022-02-02T01:08:57Z,0,"this is exactly what i was looking for, instead of defining all of the exceptions i wanted to print a message when an unwanted value was the input",True
@user-pe9qg3hg3k,2022-01-26T21:37:41Z,1,"I saw a video before where someone said that to use try: / except: was bad because they said if something fails it should just break, but they totally missed the point of it. Try except is super useful when paired in while loops with booleans to determine whether user input is able to be converted with no issue, for example",True
@muntadher8087,2022-01-05T06:05:19Z,0,"Thank you so much, god bless you!",True
@soroushsoltani919,2021-12-31T20:28:33Z,0,Your nice sir !  i was absent in the classroom but i had the opportunity to learn it here,True
@rafy-ivanmorales3077,2021-12-30T12:42:53Z,0,"I‚Äôm a new student and need help to do this project: I have a port scanner script it works properly, it works in Pycharm using python3.9. I have to make a file I did make call (Example.txt) On this file, I have to do this: 3. If the Ports is open, it should create a file and add an entry for port number  4. In case of any exception for instance ‚Äúhost is not available‚Äù, ‚Äúhost name could not be resolved‚Äù or  due to any other error, you need to write that exception into the same file. I‚Äôm not asking for you to do the project for me, I'm only asking ware I need to work or used in my script to accomplish this because it is my first time doing this and working with python too, and I have been struggling with this part one very bad. I can even send you the code, so you can look and only tell me, what I‚Äôm doing bad the is not working.",True
@grim_apple3276,2021-12-22T10:35:38Z,0,was helpful thnx,True
@suleymanarifcakr3609,2021-12-03T22:36:54Z,0,Thank you so much for sharing lots of videos! They are really so helpful!,True
@suleymanarifcakr3609,2021-12-03T22:36:20Z,0,Y O U   A R E   R E A  L L Y    A W E S O M E   M A N!,True
@abhimanyudevadhe9613,2021-12-01T05:15:27Z,0,sir which key you have used for comment out code..??,True
@shashidharsunnapu3522,2021-11-28T11:48:27Z,0,ERROR:root:'NoneType' object is not subscriptable I'm getting error when I try to store the user data into mysql db. Please help in solving this,True
@zapxcero,2021-11-26T02:01:43Z,0,Wait. You're not supposed to put a whole block of statements in try block?,True
@ainulwadhihahabdulrahim2915,2021-11-11T17:21:21Z,0,Do you know how to handle keyboard interrupt for child process in a multiprocessing?,True
@kpwlek,2021-11-08T14:25:21Z,0,love it.,True
@marcello4258,2021-11-02T12:52:42Z,0,best tut in regards to this topic on YT this seems also to be the case for other languages not only for python,True
@shiro3940,2021-10-31T09:18:34Z,0,"I just want to  confirm that I undestand it correctly.  so the ""try"" code, is trying to execute the code we want. if there's an error, the ""except"" code is for catching that. if the ""try"" code did not throw any error, the ""else"" code gets executed, and this is where the next step of the code executed inside ""try"" should be doing next. ""finally"" will execute regardless if there's any error or not.",True
@akankshadubey2110,2021-10-26T20:50:11Z,0,Hi Corey! very well explained. Indeed it helped. Just a request to make a video on chained exceptions.,True
@demonetization6596,2021-10-26T15:03:35Z,1,"Came here because the shitty notes of my class said ‚ÄúRaise, raise is to raise an exception‚Äù without telling me what exactly raising an exception means.",True
@0xb15h4l,2021-10-07T14:39:52Z,0,amazing vid! love this,True
@el-3omda476,2021-09-20T12:06:34Z,0,THX Man <3,True
@ebateru,2021-09-16T19:30:21Z,0,"Hi Corey (and the rest of fellow students),   what's the added value of   try:      1/0 except ZeroDivisionError as e:     print(e) except BaseException as e:      print(e)  versus:   try:      1/0 except BaseException as e:      print(e)  The exact same error message gets printed.   Tnx for another great video!",True
@chaitanyayeturi1312,2021-09-05T10:36:27Z,0,"First of all, your teaching style is good, and anyone grabs ur teachings easily, and thanks for teaching us. you are the best tutor I have ever come up with in python language. can u suggest any python language book, which is best to go through other than your channel? Moreover, I am a beginner to python language I thoroughly enjoyed ur videos, if u can suggest me best python book to ur sensibility and I guess it suits me and it helps me to learn further (I like physical like books). In case if u written any books related to this language can u suggest one (or) your favorite book, please......................................",True
@proteuswave,2021-08-27T03:58:32Z,0,This is great! How would I ‚Äúignore‚Äù an exception that is part of an imported library? It pops up (3 lines we‚Äôre not added to bcp) when I try to export add to a sql database,True
@meralmaradia4774,2021-08-21T10:44:09Z,0,"you are rock man, rock, just rock (y) (y) (y)",True
@vernonchoo3940,2021-08-11T06:30:32Z,0,does the 'raise exception' means overlooked those 'except' besides 'except Exception' and directly run the 'except Exception'?,True
@SpiritOfIndiaaa,2021-08-05T08:18:01Z,0,thanks a lot ... but how to create Custom Exceptions?,True
@robbiehume9131,2021-07-13T18:10:57Z,0,"Just watched your video on context managers before this and I'm wondering which is the better approach with opening files, using a context manager or this approach? Thanks!",True
@peschebichsu,2021-07-03T10:03:36Z,0,"Your video are many years old and still on most of the topics one of the best resscource, thanks a lot!",True
@MauriceWilliams,2021-05-31T20:26:23Z,0,YEEEESSSS! Soon I will have great awesome superpowers (from knowing how to code).,True
@vijendersingh5941,2021-05-23T16:46:21Z,0,Big help üôèüôè,True
@rycitomorell5945,2021-05-05T11:32:33Z,0,You are a real life hero!,True
@laughinglady79,2021-04-28T01:16:58Z,0,how do you comment out multiple lines at once?,True
@A.O.U,2021-04-20T20:38:04Z,0,"This is how you learn something in 10 minuteS. THANK YOU SIR , your explanation is AMAZING.",True
@corneliollagas1903,2021-04-18T11:22:44Z,0,I'm Practice coding through your video and solo learn with python...sorry to my English,True
@corneliollagas1903,2021-04-18T11:20:23Z,0,"Hi sir I'm always following to your YouTube channel thank you so much, I  Have a Question for you When to use raise and assert, how to use it, and what is the difference the Raise and Assert 'Cuz  I don't Understand both of them, Thank you in Advance.   From Philippines.",True
@yashroy5682,2021-04-15T06:37:55Z,0,"Hello, I am calling all the functions in main method, it has try and except block. After executing the first function, it is not calling the next one and going to except and throwing error",True
@r01blue,2021-04-11T20:50:52Z,0,Best ever video!!! Trank you!! Regards from Argentina.!!!!,True
@indirash6916,2021-04-07T03:35:13Z,0,"Hello Corey Sir,  Its really pleasure to watch your videos about Python and study.  I have a query wrt User Defined Exceptions and asking it here as I didnt get your video on it. I hope you will make one such video for us.  Question : -> It is mandatory to inherit from Exception class to build our own User Defined Exceptions?",True
@JUDOGAR,2021-04-04T13:01:58Z,0,Excellent! Loud and clear!!!! More than most of the paid courses...Thanks a lot Teacher Corey!,True
@chborger185,2021-03-27T12:11:11Z,0,oDEAR TRACEbacks COLORcoded Flashback Or?? is a COLORhighlighted TOPdown EDITOR a PYTHONfeedback GENERATOR ??  ;)  what's new ??  VISUALdesgin in a ENVIROMENTS  listen to BARNY&& FLINTstones or??;) QSL,True
@reubenadams7054,2021-03-18T11:20:56Z,0,"*try clause* -- Runs until it finishes or an exception is raised. *except clauses* -- These are checked (and then run if the exception matches) in order if and only if an exception was raised, either until it's caught or we run out of except clauses. *else clause* -- Runs if and only if the try clause did not raise any exceptions. *finally clause* -- Always runs, even if there were exceptions and even if they weren't caught.  *code after try/except block* -- Runs if and only if no exception was raised, or one was raised but was caught.",True
@danielalegriasallo5551,2021-03-18T00:59:42Z,0,This will help make an infinite loop where the code only goes on when they input the correct value. THANKS,True
@hollyjo161821,2021-03-16T21:05:11Z,0,Had to donate - I've watched your Channel ALL Day. I have learned more than I deserve. Thank you!,True
@jessontvarghese327,2021-03-07T21:16:35Z,0,Fantastic.... Thank you so much.,True
@andrewo1072,2021-02-28T08:29:51Z,0,Thank you,True
@SquidScopes,2021-02-24T04:28:51Z,0,"from five years later, this is still useful.",True
@SK-gn3rs,2021-02-12T05:23:14Z,0,I like the video even before watching...when I see it is your video....,True
@rolandjosef7961,2021-02-09T20:09:29Z,0,One thing to take note that *Exceptions* are only used at validating user inputs. *Exceptions* are not designed to address the SyntaxError in your code.  Please correct me if I am wrong.,True
@testrabbit,2021-01-31T19:07:17Z,0,"After reading string alerting to nature of exception my brain throws a logical exception that when caught goes something like ""You almost declared a double negative. Am I to assume that the file does exist, and you're toying with me? Or, alternatively, that the (""n"") at the end of (""doesn"") exist in the spell check for English in the dictionary, therefore it is a syntactic error?   j/k, ü§ò lulZ. Good tutorial.",True
@fontawesome353,2021-01-29T12:33:57Z,1,what does pass do?,True
@Tamer_Gomaa,2021-01-25T15:56:35Z,0,Nice explanation,True
@gauravgupta9089,2021-01-24T12:28:34Z,0,really great Content! great level of explanation. Thank you :),True
@rubycon9158,2021-01-24T12:15:22Z,0,Sooo.... Should i put my entire 1200 lines of code inside the try block then?,True
@jacobreed2709,2021-01-17T22:53:21Z,0,Thank you!!,True
@carpediem73,2021-01-06T15:28:54Z,0,thank you,True
@vectorperkins4737,2021-01-04T15:54:09Z,0,invalid syntax else,True
@YP7Music,2021-01-04T03:21:33Z,0,"Really Nice... May I know how do you know if such a function fill throw a certain exception? eg. in your example how do you know if open() function will throw exception name ""FileNotFoundError"" instead of ""file_not_found_error""? Thank you...",True
@etcetc3800,2021-01-01T00:09:00Z,0,Thank God for a non-indian video.,True
@ab5848,2020-12-29T05:45:04Z,0,Thanks a ton Coreyüôè I hereby pronounce you as my ultimate Guruüôè,True
@satyamvats5438,2020-12-23T16:16:33Z,0,Very Nice ! You understand us each & every deep concepts of the functions.,True
@JoshuaDHarvey,2020-12-21T01:03:20Z,0,"Great video thank you - still not 100% clear what all the 'except' options are such as 'Exception"" or 'FileNotFound' but maybe that's in the help() docs",True
@boombot9615,2020-12-06T14:34:40Z,0,"good explanation, cleared almost all of my doubts",True
@MrJos221,2020-11-29T23:07:17Z,0,"What happen when we have a function that we are calling from other function and this two function have the try catch implemented, should the try catch be implemented in the parent function or it should be callable from the 2 functions?",True
@danielEpifanov,2020-11-29T17:42:27Z,0,probably most informative video on youtube,True
@aayushgarg12,2020-11-29T12:28:32Z,0,Thank you so much Corey sir. Your video helped a lot. Your video made my concepts clear about try/except.,True
@parthmehta8716,2020-11-24T06:56:18Z,0,What's the difference between try except and with except?,True
@paulmk2290,2020-11-20T13:32:00Z,4,"Seriously, you should consider putting together a course on Udemy, or the like. I am here now because the instructor on the course I am currently doing assumed that I knew everything you just explained. Also, I note that you covered what you are doing properly and thoroughly. Not everybody is capable of doing that.",True
@justtheinstinct4893,2020-11-20T02:04:23Z,0,Do or do not. There is no try,True
@Kevinschart,2020-11-18T09:34:20Z,0,how do you make the loop print all the exception error detail?,True
@SJ-vc2tz,2020-11-15T13:06:25Z,0,"Very clear explanation, thank you!",True
@_instanze_,2020-11-12T06:58:40Z,0,"Corey I have serious question for around 4:33. I am typing up same exact code you are:  try:     f = open('test_file.txt')     var = bad_var except FileNotFoundError:     print('Sorry. This file doesn not exist')  But when I run it, the print statement goes through instead of the 'NameError' showing as it did for you. However, if I change the order of the statements:  try:     var = bad_var     f = open('test_file.txt') except FileNotFoundError:     print('Sorry. This file doesn not exist')  Then, the 'NameError' comes up. Why am I getting different results? Does order matter? Please help.  Thanks",True
@DrWho2008t101,2020-11-12T03:15:41Z,0,appreciate your work thanks for the video keep up the good work,True
@nehmaheshnair9570,2020-11-07T08:04:17Z,0,thanks man!!!!...u really saved me..,True
@bostevens236,2020-11-05T21:41:48Z,0,You're the man,True
@naserabuobaid9524,2020-11-05T00:20:51Z,0,"Thank you, this is extremely helpful",True
@user-uu3us9ys4q,2020-11-01T09:24:05Z,0,"great explanations, thanks!",True
@gouripeddipawansreekar1752,2020-10-30T06:07:48Z,0,Can we use loops in exception block?.,True
@alainkr,2020-10-22T05:29:39Z,0,Why would you unlike this video. Don't understand. Thanks Corey,True
@MhurphyMarcelo,2020-10-09T09:43:27Z,0,"very clear, thanks!",True
@mathieuseligmann9488,2020-09-29T08:43:40Z,0,Thank you so much !!!! You have just helpt me a lot !!! 10 minutes and learning so much that is so great. Again thank you very much.,True
@oo6127,2020-09-08T04:32:04Z,0,"Is the FileNotFoundError and Exception, names that user can define or are they keywords?",True
@pengli1175,2020-08-30T03:22:48Z,1,LOVE IT,True
@SuperMechtronics,2020-08-25T02:36:00Z,0,This exception video is exceptionally excellent,True
@belalmuflih5116,2020-08-19T22:46:58Z,0,can i have more than one exception about the same error to try multiple things?,True
@ihssancanmturk3842,2020-08-18T10:05:58Z,0,"I tried try exception, with the same code you wrote, it did not work, is there any try except code for positional arguments error please?",True
@wingsonlai1132,2020-07-28T18:07:24Z,0,"I have 2 questions: (i) Is ""except"" in python equal to ""catch"" in java? (ii) Does ""except"" automatically own a ""break"" inside so the ""else"" block does not run just like loops cases?",True
@joro8604,2020-07-18T16:46:13Z,1,this tutorial was soooo good!,True
@arijitghosh6378,2020-07-16T09:31:34Z,0,How would I print the stack trace of an exception within an except block?,True
@RomanReigns-ds8hs,2020-07-15T12:02:52Z,1,Awesome content !! Thanks for these videos.,True
@parpithovas,2020-07-02T20:09:42Z,0,TKS!,True
@CarlosWashingtonMercado,2020-06-23T19:12:51Z,0,Great video.,True
@tomflynn2394,2020-06-14T06:25:57Z,1,EXCELLENT,True
@vivalavida7839,2020-06-02T05:23:29Z,1,Thanks man,True
@snssatyabhagavan,2020-05-24T13:07:36Z,0,thank you very much for this video i am struggling with it  from so many days,True
@secure_the_bags620,2020-05-24T09:06:20Z,1,Man thank you for making this video. I finally understand!!,True
@dakota5569,2020-05-20T17:41:07Z,1,I could watch this perfectly at 1.75 for a quick recap/rundown. Take my like,True
@__________6931,2020-05-19T10:11:36Z,0,Why don't we use if else statements instead?,True
@younghwanchae1422,2020-05-14T21:33:12Z,1,"The way you teach how to program is so great, not to mention the contents.",True
@piersilviolongo2028,2020-05-11T07:13:26Z,0,What's the point of finally? I could just write the code without indenting it and it would run the same... I don't get why you should put 'finally',True
@sunithabinu4543,2020-05-08T07:37:37Z,1,Thank you soo much this video,True
@sunithabinu4543,2020-05-08T07:28:39Z,0,"could you please make a video on stdout,stdin ,stderr in python",True
@gamerpro021,2020-05-06T01:30:58Z,0,do exceptions haves to be long and is this one and exception handling try:                                                                                                                                    tkinter                                                                                                                              except:                                                                                                                               import error,True
@sualehqureshi4570,2020-05-01T00:21:09Z,0,"Hi thanks for the detailed explanation. I have a question if you can help!!! I am connected to a postgresql database and accessing one of it‚Äôs table content using psycopg2, due to some special character present in the data i am getting an error. As the data set contains million of records it may contain dozens of records with such characters  and i want to avoid interruption of code in later stage. i want my code to ignore the record for such cases. Can you please tell me how can i achieve that using try catch approach. Or if any other better suggestions you have. It wud help if  you reply thank you.",True
@ViralKiller,2020-04-29T22:36:44Z,47,"raise Exceptions lol, I just want to get rid of them all",True
@ShahTV,2020-04-26T23:06:10Z,0,Nice video,True
@sixie6e,2020-04-25T14:24:03Z,0,"other python videos, the person just narrates what they are doing without successfully explaining the concepts behind it. this is why you need to watch corey's videos. he doesn't make videos to show others he can code, he makes them so others can LEARN!",True
@bluestar8652,2020-04-21T01:54:38Z,0,"according to what you said, I was expecting you to put ""f.close()"" in ""finally"", was it just a mistake or is there actual reason behind this?",True
@F3ND1MUS,2020-04-20T20:25:18Z,0,"I needed this info, THANK YOU!",True
@nitkap441,2020-04-18T12:45:38Z,3,"You are awesome. As I had remarked in another of your video, you are the most efficient learning resource... Each minute is worth it. In other places, I feel like a 30 minute video should ve edited to 15-18min so that I can get the real stuff... Here I get every minutes worth... The learning is very very efficient for me!",True
@kenrosenberg8835,2020-04-14T17:38:14Z,1,"Short and simple, great video",True
@ymany3277,2020-04-02T20:59:03Z,1,amazing video and very simple and clear explanation.,True
@AdamThao92,2020-03-28T20:09:22Z,367,Better content here than most paid-training content.,True
@moebrown31092,2020-03-26T00:33:58Z,0,"I'm getting an default 'except:' must be last error on below code...any suggestions   try:     range2 = int(input('Enter Low Range:')) except:     print(""You have to enter a number"")     range1 = int(input('Enter High Range:')) except:     print(""You have to enter a number"")",True
@danielgerman4757,2020-02-21T07:17:19Z,3,"This type of good explaining that you do, should be taught to teachers! Thank you for all your hard work and dedication.",True
@hafeezshaik1221,2020-02-20T11:34:59Z,1,"Actually i want to log the excepation error and my manual error in logging file , who can i do that? This is my code try:         result=Customer.objects.all()         if result== DoesNotExist            raise Exception            except DoesNotExist  as e:         logging.exception(e)     except Exception as e:         logger.exception(""Does not find record"")",True
@Xaminn,2020-02-08T04:51:31Z,385,*Puts entire project inside a Try and Except block*,True
@ericettorres7970,2020-02-05T21:52:05Z,3,"Quick question...  Would't the ""f.close"" be better placed after the ""finally""? It seems to me that if your code throws an exception you would never reach the else statement therefore never close the file.",True
@michaelhagans965,2020-02-05T00:59:00Z,1,Awesome. Thanks for clearing that up for me.   You can also raise your own custom exception such as: 'raise Exception('This is a custom error you can create.'),True
@reemashrestha9718,2020-01-26T14:53:18Z,0,*10:09 why doesn't it print Error! instead of Currupt File! ?,True
@danrussell_official,2020-01-25T09:39:12Z,1,Thank you so much,True
@cibelless510,2020-01-16T07:08:43Z,1,"Always a surprise video. Other guys are good too, but they are a little confuse some times. But you always very clear such as ...Begin --- middle ---End....Good for you man.",True
@scarletzyy,2020-01-10T06:30:36Z,1,"Well explained. Thanks a lot, mate!",True
@nirayah,2020-01-09T20:16:15Z,2,Very good explanation. Thank you!,True
@torque6389,2020-01-04T03:54:10Z,0,Awesome,True
@lindenlonsdale8753,2020-01-03T10:33:55Z,0,Great video. Do you have one on how to write your own exceptions? Could you post a link if you do?,True
@julijanaskova438,2019-12-06T00:49:50Z,1,"Very clearly organized and explained, thanks!",True
@whalingwithishmael7751,2019-12-01T18:58:30Z,0,How did he comment out several lines at the same time?,True
@soumyazyx,2019-11-24T05:24:56Z,14,Thank you Corey for your time and effort. Keep spreading the knowledge.,True
@youssefmohamed-jt8qp,2019-11-23T00:49:27Z,1,thank you so much,True
@terguunzoregtiin8791,2019-11-02T08:52:07Z,3,"Hope I saw this earlier. And I have a question, when should we use exception handling? When opening file or handling user input, I know we should use it. But on other circumenstances, I'm not sure. So could you please explain when it should be used? Thanks in advance.",True
@haneulkim4902,2019-10-31T10:35:02Z,1,Compared to if statement how is its performance?,True
@edgarlip2,2019-09-30T11:51:19Z,2,"awesome as usual  !!! just wanted to add some little detail about the raise , u can do it like       if(name == ''):         raise Exception('name is empty , please specify a name !')",True
@allasrinivasulu1464,2019-09-30T01:39:19Z,0,Thank you sir please lploaf some best trics and tips on pythan,True
@jm10oct,2019-09-10T12:10:06Z,1,These videos are excellent!!! but i want to ask about the 'raise' you got in the end. Why did e value on the 'except' line didnt got any value?,True
@mk143mj,2019-08-27T04:14:28Z,0,For keyerror in dictionary what if two errors occurs at the same time and which will be handled first,True
@yuezhao9298,2019-08-20T18:28:23Z,0,"very nice video. many thanks! If I wrote codes outside the try block, is it equivalent to putting the codes inside the finally block?",True
@Reneeke9,2019-08-18T09:04:31Z,0,"Hi Corey, I want to use exceptions in a class, is that possible? I need to throw a message when the user is not initalizing the instance in the right way. They have to input a date, so that's Always tricky. Here's the code:  class Wedstrijd(object):      try:          def __init__(self, plaats, year,month,day, vertrekpunt, hour,minutes):              """""" please define the location, year(yyyy), month(mm), day(dd), leaving point, leaving hour(hh) and leaving minutes(mm) """"""              import datetime              self.plaats = plaats              self.datum = datetime.date(year,month,day)              self.vertrekpunt = vertrekpunt              self.vertrektijd = datetime.time(hour,minutes)      except TypeError:          help(Wedstrijd.__init__)   test = Wedstrijd('limburg', 2019,4,'Maastricht', 15,1)  print(test.vertrektijd)  print(test.datum)   Instead of running the except bloek, it just gives me the TypeError:   TypeError: __init__() missing 1 required positional argument: 'minutes'   Why doesn't it run the exception block in this class?",True
@carlosmarx3193,2019-08-09T03:40:06Z,0,"I'm failing to handle errors on loops, anyone to recommend me of an example I can refer to.plz",True
@SagnikDuttaegor92,2019-08-08T12:22:10Z,1,Awesome!!!,True
@Balaji-qx3ul,2019-08-01T14:50:05Z,0,"@9:45 I think its not working any more in Python 3. Instead of getting to the ""Exception"" block it prints from the ""FileNotFoundError"" block. Unless you move the ""Exception"" block above the ""FNFR"" block the same message gets printed.",True
@mohindersingh0711,2019-07-12T00:32:06Z,0,How to give custom error message on raise exception?,True
@juehuanliu6200,2019-06-25T20:30:51Z,1,does 'finally' must execute? for example: the 'try'  is in a loop and there is 'continue' somewhere above. Thank you!,True
@tumul1474,2019-06-05T12:41:07Z,2,thanks a lot Sir!,True
@inuken9561,2019-05-30T12:11:55Z,0,Sir How to uncomment code like the way you do. Thats so cool!,True
@bikeshtiwari,2019-05-13T02:46:36Z,2,You made me learn many concepts in python. Ur awesone teacher,True
@manjitsingh1124,2019-05-11T18:57:11Z,2,Thanks for the lesson Corey !,True
@dmitrirs5314,2019-05-07T18:51:20Z,1,"I did an improved version of the game xd, but thanks for the idea.",True
@Parvej669,2019-05-06T17:48:38Z,2,Thanks for the video. I learned Exception handling from here.,True
@adnankaya,2019-05-01T11:11:30Z,0,"Thank you for great tutorials Corey! I want to tell you that can you remove django & flask tutorial videos from ""Python Tutorials"" PLAYLIST ? They are already in their playlist. We don't want to face with them while learning python basics.",True
@oceansblue692,2019-04-30T05:12:45Z,0,@ min 8:25  what do you mean by make sure you close down the DB?,True
@jaker9007,2019-04-24T06:05:20Z,0,"I got only one question Corey. Where I can read about exception types, the ones like 'FileNotFoundError'",True
@jeremypalmer9028,2019-04-23T21:04:19Z,0,"I am curious, what is the advantage of ""finally"", why would you not just drop down out of the try block and execute the next piece of code?",True
@alexandrucretu1016,2019-04-18T09:46:21Z,4,"Your videos are very helpful, Corey! tyvm Also, just to point out that it is better to close the file (f.close()) within the finally block, because it will be executed anyway, while the else block runs only if the try clause doesn't raise an exception.",True
@ntariq1,2019-04-16T12:34:37Z,1,Very nice üëèüëè,True
@kimcato5326,2019-04-10T19:45:14Z,54,I love your videos! They are very well explained and short... better than my professor's. I am writing better programs because of your videos. Your videos are a GOD send.,True
@AlexBerkk,2019-04-04T21:24:41Z,0,"I don't get, why waht is purpose of 'finally' if you can just put the code after the 'try' block. Someone, please, explain what am i missing here?",True
@ecniv5991,2019-03-15T12:44:32Z,1,ty,True
@ManojKumar-1985,2019-03-11T07:01:44Z,4,Excellent explanation as to when to use this.Also by showing an example the concept just sits in head :-) Good job Corey,True
@FeedFall8,2019-02-17T21:39:32Z,4,This video Helped ALOT! in my game development,True
@dp0813,2019-02-17T19:07:54Z,119,"word = 'currupt' try:     if word != 'corrupt':          raise ValueError except ValueError:      print(""Corrupt is spelled wrong!"")   >>> Corrupt is spelled wrong!   :-D",True
@isaaclee0526,2019-02-08T14:29:54Z,0,"Hi Corey Schafer   I have a question for python   I don't how to do my homework    my homework is - write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7,2,bob,10 and 4 and match the output below.    Invalid input  Maximum is 10  Minimum is 2    This is my work    largest = None    smallest = None        while True:     num = input ('Enter a number')     if num == 'done' : break     try:      number = float(num)     except:      print('Invalid input')          for value in (number):     if largest is None :      largest = value     elif float(value) < float(largest):      largest = value     print('Maximum is' ,largest)        for value in (number):     if smallest is None:      smallest = value     elif float(value) > float(smallest):      smallest = value     print('Minimun is' ,smallest)      but the output is not    Invalid input    Maximum is 10    Minimum is 2      I want to know where is wrong   Please help me",True
@moazelsawaf2000,2019-02-08T14:16:53Z,1,Thanks a lot sir ‚ù§,True
@kabelomayisa6276,2019-02-05T09:52:39Z,0,really helpful ... thank you !!,True
@philippfrogel9355,2019-01-31T20:25:07Z,1,such a good video!,True
@crazyvashisth,2019-01-29T17:03:06Z,5,Now that's how to explain. Well done CoreyüòÑüòÑüòÑüòÑüçª,True
@fiziwee386,2019-01-09T20:44:31Z,0,"5:32 if the file is not found, why does this execute the second error code and not the first one? The first exception is FileNotFoundError, so why is that not executed?",True
@ineedsolution,2019-01-05T10:31:31Z,17,This the best explanation of try / except concept ever.,True
@opiyosebastian50,2019-01-02T19:26:05Z,8,Thank you Corey....I continue to follow and grow as a self made developer. You my best teacher!!,True
@beautifullove5045,2018-12-29T09:56:27Z,0,erro : https://www.youtube.com/watch?v=PbLtyVcMrk0,True
@hashpuppy5330,2018-12-21T10:17:40Z,0,Can you please make a tutorial for Python Async/Await that is easy to understand.,True
@damodarsahu3868,2018-12-20T08:55:14Z,0,can i get my current timezone in a python program?,True
@navidmohammadzadeh2141,2018-12-18T09:56:01Z,4,The best tutor ever! The best in the world! Thank you so much!,True
@michelkant,2018-12-14T10:40:59Z,0,This is so interesting and makes it nicer to experiment with code. The question then becomes: Don't you use this everywhere in your code?,True
@sra1utube,2018-11-20T01:48:22Z,0,"Whats wrong with audio of all your videos sir? I tried running these videos in different browsers, only your videos seem to be having this problem. The audio is broken and inconsistent. Please fix it.",True
@poornapragnams1622,2018-11-09T06:35:49Z,0,Nice one.. I have some detailed explanation on various possible exception handling in Python  here : https://youtu.be/RuOQNEts13w,True
@mrmoinn,2018-11-05T05:36:50Z,0,Can you name your custom exception anything you want or does it have to be a python exception,True
@RealToriMan,2018-10-24T12:07:34Z,3,Best teacher ever <3,True
@mosadoluwaagbonyin925,2018-10-14T17:50:33Z,0,"Thanks so much for the video but what if you want to define the object ""f"" to be something else in the except clause, like except: f=open(""another_file.txt"")",True
@trouserpython3857,2018-10-13T23:56:03Z,2,"Schafer bro, your like to dislike ratio on your videos if off the hisayy",True
@aku_11_11,2018-10-10T18:50:07Z,0,Sir which version of python u r using...,True
@eugenepashch5213,2018-10-06T07:40:55Z,1,Good video! Thanks!,True
@manuzsanand,2018-09-23T20:50:16Z,2,Very well explained. Thank you.,True
@wallacesantos0,2018-09-06T15:51:59Z,0,"Why would we need to use ""finally"" if we just skip the Finally keyword, the code will execute anyways regardless what happen in the try/except?",True
@josepharcilaable,2018-09-04T22:30:54Z,0,"thanks for the video WHERE CAN I GET MORE INFO ABOUT THE ""as"" KEYWORD THAT YOU USED ON MINUTE 6?",True
@RAndrewNeal,2018-08-31T16:03:14Z,0,"Wow, I've been doing this the hard way, using if statements. Manually parsing arguments AND errors. lol I gotta learn how to use argparse at some point.",True
@tienanzhang6317,2018-08-30T01:23:27Z,0,"Can python automatically raises custom exception, i.e., not explicitly raising it ? I googled a lot and found every tutorial manually raises custom exception. This means we have to use if-else to judge when to raise exception. Since we have used if-else to know whether custom exception occurs, why do we need raise an exception? Can't we address it in if block?",True
@ragtop63,2018-08-13T02:12:33Z,0,I'd love to see a real world use case,True
@michaeldaffodil2257,2018-08-04T21:48:55Z,0,"Hi, I have problem.  That line var = bad_var (3:17) I think Python ignore so there isn't unhandled exception. I have Python 3.7. So maybe in this version is not possible to have multiple codes in one Try: block. I look forward your help Correy or someone else. Best regards",True
@josekodek4938,2018-08-03T19:50:41Z,5,You have helped me really a lot in learning programming Allah Bless you Mr.Corey Schafer,True
@AshishBansal.74,2018-07-29T17:17:09Z,0,this is just awesome .... quite clear explanation ... thanks :),True
@muhammedhatem4985,2018-07-24T14:49:10Z,1,You `re Awesome Man!,True
@ifredpingplay468,2018-07-22T11:21:12Z,1,"such a nice explanation very understandable for beginners and learners aaaa but is something wrong  in my python shell ""FileNotFoundError"" is not found nor even script but its showing me the subclass of ""FileNotFoundError"" that is OSError",True
@johnvictorengland7703,2018-07-13T12:13:53Z,4,"Finally somebody who explains it well, in proper English and concisely.",True
@IamKhoramdin,2018-07-13T09:19:13Z,0,Thank you very much,True
@mehdijb752,2018-07-09T11:01:54Z,1,great job thanks,True
@tejasarlimatti8420,2018-06-28T11:03:37Z,0,your spelling is a little currupt..,True
@srinivastech1072,2018-06-17T14:15:22Z,0,"I want to create pie charts using python, but i didn't found the proper information about which packages i have to use. Can u please suggest any packages for generating pie charts",True
@anshumans1174,2018-06-15T08:28:29Z,1,"Can someone help with this issue? variable progress_str is not updating and stays as '***...'  #Hangman game import random   def welcome():     print('Hello! Welcome to Hangman!')     #print('In this game, you guess letters that you think are in a word.')     #print('You cannot see the word right away, but you can see how many letters it is.')     #print('There is a catch! Each time you guess a letter incorrectly, you lose a life. If you lose all 8 lives, you lose :(')     #print('Good luck!\n')  #Determine the word, and set up the list word_bank = ['dog'] #Only 1 for testing chosen_word = random.choice(word_bank) list_chosen_word = list(chosen_word)  #For dog would be ['d', 'o', 'g']  #Extra variables lives = 8 game_on = True progress = []  for letter in (chosen_word):     progress.append('*')  def display_lives():     print(f'You have {lives} lives remaining\n')  #To display progress as a string... progress_str = ''.join(progress)                                                    #ERROR?#  def edit_progress():     if guess in chosen_word:         for i in range(len(chosen_word)):             if guess == chosen_word[i]:                 progress[i] = guess             else:                 continue     else:         print('You guessed incorrectly! You lose a life.\n')         global lives         lives -= 1  #Start game welcome()  print(progress_str)  while game_on:      display_lives()      #Ask for player input (variable=guess)     guess = input('Please guess a letter: \n').lower()      edit_progress()     print(progress)              print(progress_str)                                      #ERROR# It is not updating!      if '*' not in progress:         win = True         game_on = False     elif lives == 0:         win = False         game_on = False    if win:     print(f'You have won with {lives} lives remaining.') else:     print('You have run out of lives! Better luck next time.')",True
@thejet4244,2018-06-14T14:02:56Z,1,Great video!,True
@jamesavery3110,2018-06-05T16:17:31Z,0,what are you using with sublime? It looks great.,True
@doeoladimeji2008,2018-05-30T01:43:48Z,0,"does one have to use ""e"" in the ""Exception as"" statement or it works with other characters?",True
@doeoladimeji2008,2018-05-30T01:43:29Z,0,"does one have to use ""e"" in the ""Exception as"" statement or it works with other characters?",True
@niteshtiwari1828,2018-05-17T04:34:24Z,1,Best explanation about exceptional handling,True
@SendiSiradj,2018-05-16T07:04:27Z,2,"sir, i still don't understand why we need to put the code in 'else' block instead of 'try' block. won't it be the same? btw, your explanation is good and easy to understand. I would be glad if you answer my question, thank you",True
@junaidjawedkhan5888,2018-05-16T00:20:00Z,3,This is the best explanation  I've read! - Thank you!,True
@joeclark-mcghee2638,2018-05-12T14:23:36Z,0,"Thanks man, very good",True
@Samto2000,2018-05-12T08:22:15Z,0,plz tel me  which library is good to use for fintech ?,True
@user-es6kq5ky7n,2018-05-11T13:42:40Z,0,Great stuff to watch videos like this when you're having your meal and can't read books),True
@lokeshharad1164,2018-05-06T20:08:45Z,0,If we want to do try except for two variables  like  A= input () # we input as string  Error # print error  B= input() #  as string  Error # print error Print (a+b) # a and b should float  How can we do this,True
@iamgalaxey,2018-05-05T00:49:28Z,11,My class doesn't explain this as well as you do i was able to easily understand this after watching this video. thank you!,True
@gledhillholdingsptyltd2654,2018-05-01T01:52:12Z,0,Best Python tute on the web,True
@officesuperhero9611,2018-04-28T16:56:24Z,1,"Another awesome video, Corey!  Amazingly clear and concise.  Thank you.",True
@sayantanghosh745,2018-04-18T10:25:54Z,0,Can I put try and except inside finally block?,True
@PamirTea,2018-04-12T00:25:46Z,0,"Great video, thank you.",True
@szenghoe,2018-03-25T13:21:08Z,1,Thank you very much!  your tutorial series is really helpful!,True
@deveagle6193,2018-03-23T22:54:27Z,0,LOVE your Python videos!,True
@tnnenkaka66,2018-03-21T00:32:15Z,0,i'm sorry but i don't understand the difference between Exception and FileNotFoundError. can you clarify?,True
@hassanlaghbi7047,2018-03-13T10:24:36Z,1,Thanks! Helpful video!,True
@vinayakhosamani7508,2018-02-28T10:00:55Z,0,"Hello anyone,is there any command to check all available modules like os,re,unittest etc in python",True
@vinayakhosamani7508,2018-02-28T09:59:54Z,0,"Hello sir,FileNotFoundError comes in which module sir? and how do I get all other exceptions types",True
@publicshared1780,2018-02-24T00:14:41Z,0,Great video. Thanks,True
@Kelvo980908,2018-02-06T15:30:29Z,1,Thank you! Much better than how my professor explained it.,True
@andreramos3026,2018-01-17T12:42:50Z,0,Thanks for your help! Success!,True
@varuntulasi6459,2018-01-05T14:10:51Z,0,How did you comment multiple lines together in 31 sec of the video?,True
@yixunnnn,2018-01-01T15:17:44Z,0,You da real mvp,True
@urbandude823,2017-12-30T18:41:06Z,0,"I've been trying to learn how to do a working try/except for like a year, and nothing made sense until now. Thank you!",True
@prashantpant2876,2017-12-20T19:29:56Z,0,"Why would we raise exceptions, doesn't this mean we are ourselves causing problem to our codes.",True
@ranjanadhingra3525,2017-12-19T19:57:43Z,0,thx,True
@himanshuladia9099,2017-12-11T08:12:45Z,0,"Ain't the finally block redundant? I mean, that anything after the try and except blocks has to be executed anyways. So, what's the use of finally?",True
@jhpk4495,2017-12-08T14:16:00Z,7,Thank you so much thats what i need for my program! and also you helped me in mastering python! keep up the great work!.,True
@Altair19979752S,2017-12-07T19:30:47Z,0,"As i just experienced (im a noob in python btw) the ""else"" part is also very important for the tryblock to work correctly, because my try-block threw an exception that wasnt catched seemingly because i had other code in my tryblock, which should have been executed afterwards. I took this other code out and now the try block catches everything.",True
@abdelhadialhnsh7228,2017-12-06T17:41:30Z,2,"I have looked around to understand this topic and finally, I found the best explanation ........good job ...please keep going and share more tutorials",True
@xdisasterology,2017-11-21T04:23:12Z,0,Thanks for the clarification!,True
@joshualipovetsky2744,2017-11-16T18:51:34Z,0,"Excellent video, Corey! Thanks so much!",True
@Ather178,2017-11-15T23:46:07Z,0,"Excellent explanation, thanks a lot! :)",True
@gamesteve360,2017-11-11T18:58:14Z,0,best teacher ever!,True
@ramasubbareddy6147,2017-11-06T10:20:40Z,0,superb explanation on exception handling in python,True
@DonDynAyt,2017-10-30T16:08:42Z,1,"Hi Corey, I just wanted to tell you how much I appreciate your videos. You're doing a great job, clear and concise. Thanks!",True
@BaccardiIsland,2017-10-26T18:39:31Z,0,"Thanks for that great video. One question: If I run multiple things under try:, as you did with f and var. Is there a possibility that it will not give  just ""Error"" if one of them is wrong but gives me at least the one which is correct? Or do  I have to run a ""try:"" for every single variable in this case? Hope my question is comprehensibly...",True
@tonychen3306,2017-10-25T17:23:58Z,0,Is there any practice that you recommend?,True
@koteswararaogudla2675,2017-10-23T06:28:50Z,0,Loved the way when you started with pass statements dude.. thank you,True
@noelrivero8070,2017-10-11T17:36:25Z,0,This videos are so helpful.,True
@parizer1983,2017-10-02T01:21:59Z,0,"3:45 ""...now we can see that we get regular Python traceback, which is a good thing..."" Why is that a good thing, wasn't the purpose of except to hide that traceback (or built-in python exception) from the user and to display some custom print message?",True
@alfx4356,2017-09-26T20:39:59Z,0,thanks for sharing!,True
@12notank,2017-09-22T11:31:09Z,1,"Hi Corey, thanks for such wonderful videos. I want to thank you for all your efforts. Also, I would like to know what is the actual need for 'else' in this try-catch flow? Without 'else' also, the program continues execution if no exception occurs.",True
@shijingsi8288,2017-09-16T09:54:18Z,0,What does the letter 'e' mean  in FileNotFound as e? Did you just use a random letter?,True
@ashishgarg3924,2017-09-13T20:54:06Z,0,you are  working in python3,True
@darthvador3699,2017-09-01T05:49:37Z,0,Literally one fucking dislike,True
@darthvador3699,2017-09-01T05:45:47Z,0,"Try:      #entire code Except:     print(""I'm done with coding forever, fuck you"")",True
@paul8683,2017-08-22T17:57:47Z,525,You sir are a gift to amateur programmers.,True
@sudipta_samanta,2017-08-20T14:09:28Z,0,"Can you please tell me why the input() method is getting EOF error, and how can I bypass this error and get the value from user ?",True
@NetMistro,2017-08-15T02:50:14Z,0,great videos man...,True
@KARAB1NAS,2017-08-01T17:16:07Z,0,Great!!,True
@halehallamehhaery1803,2017-07-10T09:15:08Z,0,thanks a lot,True
@imranmarwat8646,2017-07-09T14:08:18Z,0,"Hey hope you see this and reply. I wrote the same except FileNotFoundError: you wrote in this video and I keep getting ""FileNotFoundError is not defined"". Not sure why this is if its a built in exception?",True
@nikolahuang1919,2017-07-08T23:15:11Z,0,too good. So clear and no strange accent.,True
@VelezBiH,2017-07-02T16:26:21Z,1,Thank you for explain the error handling in python. You are my favorite Youtube teacher on python!,True
@akanimoakwa1892,2017-05-25T12:35:23Z,0,Thanks bro. You explained the topic so well. I am really grateful.,True
@prithvib8662,2017-05-01T06:52:43Z,0,Is FileNotFOundError a special keyword for that type of error?,True
@panicbydesign7315,2017-04-25T20:58:10Z,121,I have been looking everywhere and just could not wrap my head around multiple exceptions. Your explanation is succinct and well demonstrated. THANK YOU! I will be going back and watching the rest of your tutorials.,True
@01psychosocial10,2017-04-15T12:39:49Z,0,Wouldn't it be good to put the f.close() in finally?  So your file would be closed no matter what?,True
@KamalNayanlotus,2017-03-27T04:09:16Z,0,"very well explained ,sir !!",True
@mciniell,2017-03-22T14:37:50Z,0,Great video! Is the code posted anywhere?,True
@suryapraharsha5497,2017-03-21T12:37:09Z,0,Nice and clearly explained!!  thank you,True
@Bad_Horsey,2017-03-18T22:03:38Z,0,"Very clear, thank you!",True
@adamsmith5374,2017-03-12T22:23:30Z,0,This video helped me a great deal to wrap my head around this topic. Thank you very much!,True
@Linux4Ever2011,2017-03-12T16:50:00Z,0,"That's really helpful, thanks a lot :)",True
@Accubus,2017-03-02T17:23:54Z,0,how do you run python in sublime text?,True
@noiedwavve7494,2017-02-27T06:05:16Z,0,What do you mean clean up code ?,True
@ApplySkills,2017-02-19T09:04:45Z,8,damn 280 likes and no dislikes? This is my opportunity to be first,True
@alfx4356,2017-02-18T07:34:06Z,0,thanks a lot for the super clear explanation!,True
@silverflash1675,2017-01-26T12:05:39Z,19,explained very well! thank you,True
@mrYtuser01,2016-12-10T22:29:58Z,0,Perfect,True
@sdmurff,2016-12-09T04:28:24Z,0,"Good intro, thank you!",True
@sarchstar,2016-12-08T04:53:27Z,0,ahhh so helpful thank you!,True
@Qornv,2016-12-06T23:48:03Z,12,"Did you mean ""corrupt""... ?",True
@MrVwin,2016-11-26T20:32:19Z,2,Perfect Tutorial. Thank you Corey,True
@seattletcp1,2016-11-17T06:28:06Z,0,nice and well explained in a simple way! Thank you!,True
@Stardust342,2016-11-16T23:14:04Z,0,The 60fps was enough to give be a master's in Computer Science,True
@SuperPradeep01,2016-11-15T12:17:16Z,0,Awesome Tutorial ...,True
@maverickice8664,2016-09-29T05:58:18Z,0,hi very helpful tutorials. can you please tell me what editor are you using? and how can i use the same? thanks,True
@CodingMazaa,2016-09-15T14:14:14Z,0,Personally I prefer Anaconda and Spyder IDE,True
@shubhamkapoor3621,2016-08-13T03:13:12Z,1,"nice video sir,what idle  r u  using? it's different and advance.are u customize idle of phython 3.5?",True
@Dan-tf9kb,2016-08-07T21:54:13Z,0,Great video as always,True
@Crisp3333,2016-07-30T15:17:47Z,0,what IDE are you using?,True
@pa1kum6,2016-07-01T02:14:55Z,0,is the below way of writing exceptions common?  I am always confused how to handle case where multiple blocks of code (which are not immediate) can cause exceptions...  add a try block  try:    <code you think could cause exception> except:     <exception handling for the code in try block> else:     <continue with the code related to try block> finally:      <clean up part in case of exception??>  few lines of normal code... .... ....  and then another try block... try:    <code you think could cause exception> except:     <exception handling for the code in try block> else:     <continue with the code related to try block> finally:      <clean up part in case of exception??>,True
@NelsonMandelanelly,2016-06-17T12:56:46Z,1,This was helpful thanks.,True
@noedelacruz3455,2016-05-29T10:50:04Z,0,"This was very is, thank you.",True
@ahervert551,2016-05-23T11:20:20Z,0,Very well done,True
@sistemamarco,2016-04-09T07:37:55Z,0,Great video. Well done.,True
@Assanken,2015-12-21T06:07:53Z,0,The most vivid and comprehensive explanations ever! Great videos.,True
@AhmedBalfaqih,2015-11-19T22:59:33Z,0,Really great and simple. Thank you. I have a simple question. How do I exit the whole program cleanly after an exception is raised?,True
@akinkanju9653,2015-11-13T20:36:32Z,2,"Corey, thanks for these useful videos.  I've watched all your videos about Python.  Please consider covering scraping and regular expressions.  Cheers!",True
