author,updated_at,like_count,text,public
@weiyixiao2870,2023-01-31T22:18:27Z,0,"Somehow, I have to say that I really love the cup collection, from donut to wheals to â€¦ to octopus XD",True
@darkjedeye5064,2023-01-17T06:12:34Z,0,"to roll back, delete the sqlite3 db, remove all pycache and migrations, then create the db again. only thing i have found that works.... on mysql, delete the tables, cahce and migrations",True
@fabbae215,2022-03-11T09:08:02Z,0,"Great tutorial sentdex! I'm a Python and Django beginner, I would like to ask how can I return a field from another class (let's say tutorial_series from class ""TutorialSeries"") inside an __str__ in another class (returning the input from tutorial_series of class ""Tutorial Series"" in the other class named ""Tutorial"" to be printed out using __str__ method but instead of the whole content it's only tutorial_series )?",True
@pavprograms,2022-02-25T12:17:59Z,2,Migration error solved  1. Delete all files in the migrations folder in your app except __init__.py 2. Delete db.sqlite3 file 3. Run command python ./manage.py makemigrations 4.Run command python ./manage.py migrate --run -syncdb,True
@tutorialpakbejo3004,2021-12-22T16:29:36Z,0,"if i have two tables, let say them as table 1 and table 2 and both of them have date column. i make the foreign key in table 2 relate to table 1. what i get in table 2 only the date_id and it just an integer value. How can i Get the real date value (not integer as date_id) from table 1? in this case, i really need to access the date column from table 2 not table 1.",True
@deadwarrior9866,2021-11-29T09:50:23Z,0,these are junk bro teach us how u make api of them,True
@TheSimschap,2021-07-18T17:57:05Z,0,"after implementing, when I try to access admin (http://127.0.0.1:8000/admin) I get the information that this is not a known category. How come I am no longer redirected to the admin page? any ideas what I might have done wrong? Cheers!",True
@vadapallichaitu8799,2021-05-01T04:53:54Z,0,"you should be confident while teaching, your lack of conviction and a goofy laugh later are really distracting.",True
@mudworld09,2021-04-22T03:21:20Z,0,"It's seems that because the error with tables, from 642 likes, in part 10 you get only half.",True
@ygcjayalal,2021-02-01T14:41:17Z,0,waiting time.,True
@ezstartup-team,2021-01-23T04:55:09Z,0,How can I connect and make table relationship from MySQL to another is Postgresql in Django multiple database feature?,True
@thehitmanvan,2021-01-17T13:55:49Z,0,im gonna be the 1m sub,True
@MsXvostik,2020-12-13T11:51:52Z,0,"Hello sentdex, thanks for the tutorial. For me it works perfect. The only problem is when i try to add / edit or delete category in admin form (with the help of icons), popup opens with the message ""localhost refused connection"" .  Any idea what i make wrong? Thanks!",True
@sureshr2968,2020-12-05T15:40:51Z,0,His laughing distracts me.,True
@darkseid6412,2020-11-04T12:33:03Z,0,THIS WAS A ROLLERCOASTER!!!,True
@suvitsharma7432,2020-10-08T09:30:48Z,0,your laugh !!! :P,True
@mycode0,2020-09-30T14:03:45Z,0,So does the ForeignKey from TutorialSearies points to Category.id or Category.tutorial_category I really got confused,True
@mycode0,2020-09-29T00:39:56Z,0,What I did to solve my migration problem was to delete all tutorials. Because somehow it was looking for category with id 2 or something like that. So if you have id miss matching that might work,True
@pratt3000,2020-09-02T05:04:37Z,0,"Okay so i went to everyone's solution... here is the gist of it........... delete the dbsqlite file, delete the migration folder files except the init.py one................. now run migration commands............... open up shell ..............   In [1]: from main.models import Tutorial                                                                                                                        In [2]: from main.models import TutorialSeries                                                                                                                  In [3]: from main.models import TutorialCategory                                                                                                                In [4]: from django.utils import timezone                                                                                                                                                                               In [5] : new_t = TutorialCategory(tutorial_category=""to be"", category_summary=""or not to be"" )                                                                   In [7]: new_t.save()                                                                                                                                            In [8]: ts = TutorialSeries(tutorial_series=""red black"", tutorial_category=new_t, series_summary=""trees"")                                                       In [9]: ts.save()                                                                                                                                               In [10]: tt = Tutorial(tutorial_title=""lol"", tutorial_content=""hi"", tutorial_published=timezone.now(), tutorial_series=ts)                                      In [11]: tt.save()  ......................................................now create superuser ..............................DONE!!",True
@junaidmahmud2894,2020-07-18T17:35:04Z,0,"Can anybody tell me why TutorialSeries did not have ""series_slug""?",True
@bishalchaulagain9660,2020-07-17T06:37:16Z,1,I get error when i try to add tutorial from the database .. does anyone have a fix.. i tried deleting the database and again running  migrations but doesn't seem to work,True
@madukomablessed4712,2020-07-13T16:04:06Z,0,"I fixed the issue, I created a new db and deleted the old one. Ran the makemigrations and migrate again, and it worked",True
@madukomablessed4712,2020-07-13T15:48:55Z,0,"Hey sentdex, I have an issue, I tried to run the makemigrations but with a postgreSQL database (which whas been working), but I got a very confusing error which I do not know where to start from. I ran the migrations with sqlite as database, no issue, But this is confusing me. This is the error:   python manage.py migrate Operations to perform:   Apply all migrations: admin, auth, contenttypes, main, sessions Running migrations: C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\fields\__init__.py:1361: RuntimeWarning: DateTimeField Tutorial.tutorial_published received a naive datetime (2020-07-13 15:00:32.498108) while time zone support is active.   warnings.warn(""DateTimeField %s received a naive datetime (%s)""   Applying main.0002_auto_20200713_1500...Traceback (most recent call last):   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py"", line 86, in _execute     return self.cursor.execute(sql, params) psycopg2.errors.ForeignKeyViolation: insert or update on table ""main_tutorial"" violates foreign key constraint ""main_tutorial_tutorial_series_id_c730f0e6_fk_main_tuto"" DETAIL:  Key (tutorial_series_id)=(1) is not present in table ""main_tutorialseries"".   The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File ""manage.py"", line 21, in <module>     main()   File ""manage.py"", line 17, in main     execute_from_command_line(sys.argv)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py"", line 401, in execute_from_command_line     utility.execute()   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py"", line 395, in execute     self.fetch_command(subcommand).run_from_argv(self.argv)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\base.py"", line 328, in run_from_argv     self.execute(*args, **cmd_options)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\base.py"", line 369, in execute     output = self.handle(*args, **options)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\base.py"", line 83, in wrapped     res = handle_func(*args, **kwargs)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\commands\migrate.py"", line 231, in handle     post_migrate_state = executor.migrate(   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\executor.py"", line 117, in migrate     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\executor.py"", line 147, in _migrate_all_forwards     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\executor.py"", line 245, in apply_migration     state = migration.apply(state, schema_editor)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\migration.py"", line 124, in apply     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\operations\fields.py"", line 110, in database_forwards     schema_editor.add_field(   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\schema.py"", line 480, in add_field     self.execute(sql, params)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\schema.py"", line 142, in execute     cursor.execute(sql, params)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py"", line 100, in execute     return super().execute(sql, params)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py"", line 68, in execute     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py"", line 77, in _execute_with_wrappers     return executor(sql, params, many, context)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py"", line 86, in _execute     return self.cursor.execute(sql, params)   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py"", line 90, in __exit__     raise dj_exc_value.with_traceback(traceback) from exc_value   File ""C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py"", line 86, in _execute     return self.cursor.execute(sql, params) django.db.utils.IntegrityError: insert or update on table ""main_tutorial"" violates foreign key constraint ""main_tutorial_tutorial_series_id_c730f0e6_fk_main_tuto"" DETAIL:  Key (tutorial_series_id)=(1) is not present in table ""main_tutorialseries"".",True
@wiki-infodevelopment3369,2020-06-16T22:38:27Z,0,the hard thing is when you use form views to save data in your page many problem you will face.,True
@prachinainawa3055,2020-05-31T09:37:35Z,0,I like your laugh,True
@kakon_._,2020-05-24T15:09:40Z,0,i am not able to add fields of other tables except Tutorial in the TutorialAdmin class.  throws this error : Unknown field(s) please help sentdex Djano version : 2.2.3,True
@rajbanstola8730,2020-05-17T14:10:03Z,0,if migration fails try: python manage.py migrate --fake appname zero then try migrating again,True
@serenequek8483,2020-05-17T07:59:43Z,2,For the migration error that many of us are experiencing. The best thing to do is to delete your Tutorials entries that you created initially in https:127.0.0.1:8000/admin. This is because those entries do not have the foreign key that we are trying to add in.,True
@sambase123,2020-05-12T17:47:54Z,0,"Can some one explain what below code does,      class Meta:         # Gives the proper plural name for admin         verbose_name_plural = ""Categories""",True
@dhavisachan2672,2020-05-09T07:02:10Z,0,Field id expected a number but got  This error is coming I have tried  deleting migration file and re migrating but then also not working,True
@aaronbaron6468,2020-05-08T02:49:38Z,0,Part 9? It's basically the Bible since Jesus is confirmed to be a JoJo,True
@bringittolife1736,2020-04-26T16:46:49Z,0,Im pretty sure when you hit an error with a migration if I have understood your question right you can go into the app's directory that you are making the migrations to and open the folder migrations. You will be presented with files that are your migrations. With the error I had I made a migration where it stuck invalid data types into the database and so I had to locate the migration file that put this into the database and change the default. Hope this answers your question but i'm fairly new to Django so I may be wrong.,True
@lixiangxu4880,2020-04-17T06:23:55Z,23,"I solved the 'migration' problem by this way: step 1: delete db.sqlite3 step 2: run make migrations then migrate step 3: run shell, create new tutorial_category as tc, then create new tutorial_series as ts with default category as tc, and then create new_tutorial with default tutorial_series as ts, save tc, ts and new_tutorial step 4: create superuser step 5: run server, done.",True
@sidharthpunathil,2020-04-14T21:30:47Z,0,I ran into so problems when migrating the only thing I could do was to delete the db.sqlite3. Is there some other ways to recover my files if this happens again?,True
@kristimihali524,2020-02-26T15:27:45Z,0,i love you man thanks for saving my project,True
@pickprogramming4206,2020-01-23T15:00:26Z,1,"IntegrityError at /admin/main/tutorialcategory/ FOREIGN KEY constraint failed",True
@_archiesingh_,2020-01-14T10:18:08Z,1,django.db.utils.OperationalError: no such table: main_tutorialcategory PLEASE HELP,True
@shilpabhagat1675,2019-12-22T16:22:23Z,1,sir your style is too good..i understand ..,True
@paulbird2772,2019-12-11T11:49:06Z,0,At the start of this lesson I'm still waiting for you to add another Tutorial object so you  can see why they are lined up how they are :-),True
@andviktor,2019-11-28T10:49:40Z,1,"Hi! Thanks for great lesson! But, what if i have too much 'Series' with same names but in different 'Categories' like Category 1 -> Series 1 Category 1 - > Series 2 Category 2 -> Series 1 Category 3 -> Series 1 ext  and i need to show 2 fields in Tutorial edit page: Category and Series when i select Category, Series field show me just Series of selected category...  Can u help me? :'(",True
@vinayyadav2036,2019-11-01T10:35:00Z,4,django.db.utils.IntegrityError: The row in table 'main_tutorial' with primary key '1' has an invalid foreign key: main_tutorial.series_id contains a value 'series_id' that does not have a corresponding value in main_tutorialseries.id. how to solve this???  I encountered this during making migrations and migrate,True
@charisbaafi8450,2019-10-26T14:20:40Z,0,"i need help with this error      File ""C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\sqlite3\base.py"", line 383, in execute     return Database.Cursor.execute(self, query, params)  django.db.utils.OperationalError: no such table: main_tutorial",True
@yankeeownz9980,2019-10-23T18:26:43Z,0,"I followed step by step from video 1 - video 9: No issues, but once I followed all of the steps from Video 9, nothing but errors. Either a _commit(base.py in _commit, line 240) or _execute(base.py in execute, line 383) or slug error - slug was for the tutorials we made already. Steps I've tried I deleted all of the py migration files Reset the admin and model files back to what they were before adding the 2 tables from video 9 - Cannot add tutorial in the admin section Created a new superuser - did not fix any of the errors/issues.   ***If people noticed: Open up the tutorial URL and login. It turns Register to Admin within the navbar - when your hover over admin in the navbar the toast says account. When you click admin, it throws an error",True
@youtubercasual6919,2019-10-16T21:51:14Z,0,"Hi, I have a dude about compund keys and foreign keys, This is script of MySql  create table bot_carreras(  za_carrera int not null,     codigo_carrera varchar(15) not null,     nombre_carrera varchar(100) not null,     activo bit,     constraint PK_za_carrera primary key(za_carrera),     constraint UK_codigo_carrera unique(codigo_carrera),     constraint UK_nombre_carrera unique(nombre_carrera) );  create table bot_jornadas(  za_jornada int not null,     za_carrera int not null,     nombre_jornada varchar(30) not null,     activo bit not null,     constraint PK_za_jornada primary key(za_carrera,za_jornada),     constraint FK_jornadas_carreras foreign key(za_carrera)     references bot_carreras(za_carrera),  constraint UK_nombre_jornada unique(za_carrera,nombre_jornada) );  create table bot_dias_jornadas(  za_jornada int not null,     za_carrera int not null,     za_dia int not null,     dia varchar(20) not null,     activo bit not null,     constraint PK_za_dia primary key(za_carrera, za_jornada, za_dia),     constraint FK_dias_a_jornadas foreign key(za_carrera,za_jornada)     references bot_jornadas(za_carrera,za_jornada),  constraint UK_dia unique(za_carrera, za_jornada, dia) );  I can't find a way to do this because django gives me a mistake Thanks for your video too",True
@thorstenhellwig9794,2019-09-27T08:25:08Z,0,Sentdex (15:08): ... like what files do I need to modify to skip a pecific migration number ... if anybody know comment below ... :-) LOL I don't know what the hack you're watching for ... :-))))))))),True
@joaochivela8738,2019-09-25T23:36:32Z,0,how do I remove this information? This is an auto-generated Django model module.,True
@jigerjain,2019-09-19T05:50:56Z,0,"I was facing error while I was making migrations and thought of digging it. Then by looking at the comments I realized few folks had already rectified it.   The following answer has been posted by nice gentlemen namely: ""@kevin di"" and ""@JOSEPH Blessingh"". The recommendation helped me and worked like charm, thought of providing the solution on the recent comments thus:  There is a file  ""db.sqlite3 "" in your working directory, you can open it with any database management tools that supports SQLite type. following the steps:  1. For example, "" DB Browser for SQLite "", you can Google and download it. 2. Opening the "" db.sqlite3 "" file, navigate to the  Tables. 3. Find the main_tutorial table. (Maybe you used another table name in the previous lessons, use your table name.) 4. Delete record from the table: main_tutorial. 5. Try python manage.py migrate again.  The meaning of Delete Record from the table can be explained as: - Click main_tutorial - Then you might see a tab with the name Browse Data - Click it and you will see your records -  Press Ctrl + Left Mouse button on the number on the left hand side column to select all the rows - Delete them using right click",True
@RREDesigns,2019-09-17T02:06:00Z,0,"When I hit an error and I'm sure I want it all in, I delete the migration folders and the database. Then I have to create again the superuser and the content I had, but while developing you usually only have one or two entities of each kind. :D",True
@mohamedaimenhassen2440,2019-09-07T18:13:22Z,0,Congratulations for the tutorial but you know that you code wrong? almost all the views the url the slugs belong the models you code all wrong,True
@chimerablack4913,2019-09-01T23:09:35Z,0,15:30 you have to delete the migration files and have them regenerate,True
@nurbekfayziev,2019-08-22T18:10:52Z,2,Guys! I found the ACTUAL SOLUTION: Try this!: ----------- python manage.py migrate --run-syncdb -----------,True
@cuburtrivera1167,2019-08-22T14:49:11Z,1,"dang how many fancy mugs do you actually have? haha anyways, your tutorials have been really helpful during my college days, and they always will be. I could say that you're part of the reason why I was able to graduate xD. Really, thank you.",True
@sharmaayush310,2019-07-16T14:43:31Z,0,hi what to put in fields of slug in models . should it be default thats is 1 or we should put something while making categories .,True
@sakentleuberdin5917,2019-06-27T06:21:59Z,0,"Hi guys, I received the error during the migrations. Who can help to resolve it? bad_value, referenced_table_name, referenced_column_name django.db.utils.IntegrityError: The row in table 'main_tutorial' with primary key '1' has an invalid foreign key: main_tutorial.tutorial_series_id contains a value '1' that does not have a corresponding value in main_tutorialseries.id.",True
@cypherphage4294,2019-05-27T08:43:29Z,1,django.db.utils.IntegrityError: The row in table 'main_tutorial' with primary key '1' has an invalid foreign key: main_tutorial.tutorial_series_id contains a value '1' that does not have a corresponding value in main_tutorialseries.id.,True
@tbjasun,2019-05-24T14:41:50Z,0,"like many on here, I was stuck on the migrations issue and had to troubleshoot it. The models code is solid from what I can tell, and I for the life of me couldn't get it to work. I ended up following steps to junk the DB entirely, all migrations, then ran makemigrations and migrate again. It was able to get past the process of re-doing the whole thing at once. Of course you then have to run createsuperuser again, and at this point if you're following this series its not a great loss to do this and run it all together. Now my problem is running into adding actual tutorials. I can add series, and categories, but it fails when saving an actual tutorial.  I'm just now hitting this problem so I haven't searched very much yet. Anyone else have this issue please pitch in your thoughts. I'll be back on to share my fix once I get there...",True
@maximumisraelyusuf7689,2019-05-14T11:52:04Z,0,"please i keep getting migrations error , please help",True
@polyspastos,2019-05-07T05:52:25Z,0,shafted,True
@burg5165,2019-04-27T11:49:01Z,0,"I'm getting this error during migration File ""C:\Users\paolo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\sqlite3\base.py"", line 318, in check_constraints     bad_value, referenced_table_name, referenced_column_name django.db.utils.IntegrityError: The row in table 'main_tutorial' with primary key '1' has an invalid foreign key: main_tutorial.tutorial_series_id contains a value '1' that does not have a corresponding value in main_tutorialseries.id.",True
@dhanunjaypaila4865,2019-04-18T15:26:47Z,0,"I have a requirement to load Excel data to postgres in django. I have created models and loading using pandas dataframe (to_sql). Buy I have a chally here in building relationships between models. As far as I know, we can build relationships if we save model objects one by one using (onetoone, foreign key,manytomany). Please help me how to create relationships when we upload Excel data in one shot",True
@kevindi8691,2019-04-11T22:42:12Z,5,After 'python manage.py migrate'  I got this error : jango.db.utils.IntegrityError: The row in table 'main_tutorial' with primary key '1' has an invalid foreign key: main_tutorial.tutorial_series_id contains a value '1' that does not have a corresponding value in main_tutorialseries.id.  Who can help me?,True
@MrAntoAnish,2019-04-07T20:04:49Z,96,"I did have a problem during the actual migrate where in it said that the main_tutorial with id 1 doesnt have ""blah blah"" - integrity error - with main_tutorialseries   I figured this has to be because we have an actual tutorial already in db which is not linked to the tutorial series, which may cause this error. So i deleted all migrations from main folder and deleted the db.sqllite3 file. Ran make migrations and migrate again and this time it worked.   Need to create tutorials again and make sure that  they are linked to a series or else it will fail during save",True
@MuhammedMuhammed-qv3vh,2019-04-02T16:32:52Z,0,"Great video sentdex,  please how can i add image file to my TutorialCategory and TutorialSeries.",True
@dexmake,2019-03-22T22:02:24Z,0,2019 an this guy is still murdering in the django tutorial game,True
@mommachaos8586,2019-03-14T02:58:59Z,1,what is the slug category for/mean?,True
@jojogaroot,2019-03-13T09:32:13Z,4,"Dude, I lloooove you!! (not in a wrong way) can you teach us how do we store the videos for the tutorials in the database?",True
@Jojo-hr7il,2019-02-24T15:55:40Z,1,"sometimes I get error with migrations, I delete migrations files and the database (make sure not to delete init file) then i do the migrations again. I don't know really why this happen, same models I repeat the operations  then it work!",True
@dystopia2142,2019-02-21T16:58:54Z,0,16:26 that moment :),True
@romancheprack9425,2019-02-16T11:37:51Z,1,"I have been trying to delete a series or a category and got into an IntegrityError, FOREIGN KEY constraint failed. did someone get it also? been looking online for a solution without any luck. suggestions?",True
@toastrecon,2019-02-14T17:47:08Z,0,"Okay, so I might be the only one who didn't get this or notice it, but it is essential that each series have at least one tutorial. I'm not sure why, maybe I missed something else. It seems like the categories are fine without series, but the series without tutorials seems to cause an Attribute Error: ""'Tutorial' object has no attribute 'category_slug'"" Any ideas why this is so?",True
@mohamedelmistiri1689,2019-02-07T00:56:08Z,0,"Another great tutorial. I really appreciate your work, and teaching skills.   I am not sure how to roll back a migration error. But I found in this Quora post that  PostgreSQL is the best SQL engine to run with Django in terms of migrations management: https://www.quora.com/Which-database-will-work-best-with-python-Django",True
@minsik9614,2019-02-04T05:04:22Z,0,you are the best teacher! thank you!,True
@kreigrastalovich2577,2019-02-03T14:13:10Z,1,Always look out for sentdex videos for my Django/python info. One thing I originally found a pain to wrap my head around early on was routing for a number of apps using a number of dbs. Be good to see a video on this from your pov.,True
@pushpakkatkar8604,2019-02-03T14:12:15Z,1,"Im not getting category name as Fundamentals but instead im getting  ""TutorialSeries object 1""",True
@stefgou,2019-02-02T14:43:50Z,0,"To quickly ""roll back"" a migration error, can't you just go in your ""Migrations"" folder and delete the files you don't want anymore?",True
@anishjain8096,2019-02-02T05:06:20Z,0,Why you are not using slug field,True
@andreasnordenhof7250,2019-02-01T16:10:14Z,0,ThisIsPascalCase  thisIsCamelCase  difference being the first word not being upper case in camel case,True
@Skaxarrat,2019-02-01T10:55:10Z,5,"Regarding migrations, if you can make a migration but you fail to migrate it, you can try to modify it at the APP_NAME/migrations/00XX_auto_XXXXX.py. You can also squash them (AKA reduce or merging them together) with manage.py squashmigrations APP_NAME MIGRATION_NUMBER.  A migration is just a modification of the current Database on its past migration. If you don't have anything important, you can delete the migration folder and run makemigrations/migrate again. If you want to save the information you can dumpdata the information into a json and load a jjson with data with...loaddata.  Managing migrations is pretty messy, so normally google what you need to do or search it at the docs: https://docs.djangoproject.com/en/dev/topics/migrations/  P.S: Use SlugField and TextField for a Textarea widged for your summary. Django has a lot of fields (some of them related to just one a database, being PostgreSQL the best one).",True
@d415y,2019-02-01T10:47:49Z,0,"Can you please shout out James McNulty in your next video, he has just gone on a ten minute rant in our computer science lesson about how much he loves you",True
@sarmilaguha2453,2019-02-01T10:40:57Z,0,Dude....you are just....ðŸ”¥ðŸ”¥ðŸ”¥,True
@girish7914,2019-02-01T07:22:32Z,0,can you please make more videos on voice bots... thank you,True
@flynnbarnett33,2019-02-01T02:47:59Z,5,It amazes me how many interesting coffee mugs you have. (^_-) I love them,True
@ShioPK,2019-02-01T00:16:13Z,20,Could you make a tutorial about uploading/downloading files in Django?,True
@japoneon8915,2019-01-31T20:55:23Z,4,why slug is charfield ? maybe SlugField,True
@perecollfdz,2019-01-31T19:55:54Z,17,In love with your coffe cups,True
@AbhishekKumar-mq1tt,2019-01-31T19:21:25Z,2,Thank u for this awesome video and series,True
@louislane318,2019-01-31T18:56:29Z,1,Are you willing to do an updated kivy series?,True
@arubio277,2019-01-31T18:11:28Z,0,3rd comment,True
@heyoufellow,2019-01-31T18:07:35Z,0,Here's my the most favorite python's teacher ;&,True
